[package]
name = "relics-ord"
description = "⟁ Relics wallet and block explorer"
version = "0.22.0"
license = "CC0-1.0"
edition = "2021"
autotests = false
homepage = "https://github.com/relicsprotocol/relics-ord"
repository = "https://github.com/relicsprotocol/relics-ord"
autobins = false
rust-version = "1.76.0"

[package.metadata.deb]
copyright = "The (Relics) Ord Maintainers"
maintainer = "The (Relics) Ord Maintainers"

[workspace]
members = [".", "crates/*"]

[dependencies]
anyhow = { version = "1.0.90", features = ["backtrace"] }
async-trait = "0.1.72"
axum = { version = "0.6.1", features = ["http2"] }
axum-server = "0.5.0"
base64 = "0.22.0"
bincode = "1.3.3"
bip322 = "0.0.8"
bip39 = "2.0.0"
bitcoin = { version = "=0.32.3", features = ["rand", "serde"] }
bitcoincore-rpc = "0.19.0"
boilerplate = { version = "1.0.0", features = ["axum"] }
brotli = "7.0.0"
chrono = { version = "0.4.19", features = ["serde"] }
ciborium = "0.2.1"
clap = { version = "4.4.2", features = ["derive"] }
colored = "2.0.4"
ctrlc = { version = "3.2.1", features = ["termination"] }
dirs = "5.0.0"
env_logger = "0.11.0"
futures = "0.3.21"
hex = "0.4.3"
html-escaper = "0.2.0"
http = "0.2.6"
humantime = "2.1.0"
hyper = { version = "0.14.24", features = ["client", "http2"] }
indicatif = "0.17.1"
lazy_static = "1.4.0"
log = "0.4.14"
mime = "0.3.16"
mime_guess = "2.0.4"
miniscript = "12.0.0"
mp4 = "0.14.0"
ordinals = { version = "0.0.12", path = "crates/ordinals" }
redb = "2.2.0"
ref-cast = "1.0.23"
regex = "1.6.0"
relics = { version = "0.0.1", path = "crates/relics" }
reqwest = { version = "0.11.27", features = ["blocking", "json"] }
rss = "2.0.1"
rust-embed = "8.0.0"
rustls = "0.22.0"
rustls-acme = { version = "0.8.1", features = ["axum"] }
serde = { version = "1.0.137", features = ["derive"] }
serde-hex = "0.1.0"
serde_json = { version = "1.0.132", features = ["preserve_order"] }
serde_with = "3.7.0"
serde_yaml = "0.9.17"
sha3 = "0.10.8"
snafu = "0.8.3"
sysinfo = "0.32.0"
tempfile = "3.2.0"
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
tokio-stream = "0.1.9"
tokio-util = {version = "0.7.3", features = ["compat"] }
tower-http = { version = "0.4.0", features = ["auth", "compression-br", "compression-gzip", "cors", "set-header"] }
urlencoding = "2.1.3"
csv = "1.3.1"

[dev-dependencies]
criterion = "0.5.1"
executable-path = "1.0.0"
mockcore = { path = "crates/mockcore" }
nix = { version = "0.29.0", features = ["signal"] }
pretty_assertions = "1.2.1"
reqwest = { version = "0.11.27", features = ["blocking", "brotli", "json"] }
unindent = "0.2.1"

[[bin]]
name = "ord"
path = "src/bin/main.rs"

[lib]
name = "ord"
path = "src/lib.rs"

[[test]]
name = "integration"
path = "tests/lib.rs"
