[toolchain]
channel    = "1.86.0"                         # released Apr 3 2025
profile    = "minimal"
components = ["clippy", "rustfmt"]
targets    = [
  "aarch64-apple-darwin",
  "x86_64-unknown-linux-gnu"
]
